# default and the only config.yml for KnowItAllMEB
# config for STABLE versions
# version 0.0.2

#MySQL Database details
database:
    mysql:
        #MySQL server address
        host: db.screamingsandals.com
        #MySQL server port (default 3306)
        port: 3306
        #Database name (NOTE! You need to create the database, then the plugin will create the tables.)
        databaseName: 'misat11_pronze_ceph_db'
        #Tables name (the plugin will auto create it)
        dataTableName: 'eco_accounts'
        #User name
        user: 'KnowItAllNet'
        #User password
        password: 'IKeepMyPasswordsSecret'
        #SSL connection.
        sslEnabled: false
    #This maintenance task runs async with a 2 min delay after the server starts.
    removeOldAccounts:
        #Enable or disable database clean up of old accounts. | (true or false)
        enabled: false
        #Inactivity in days. Default 60 days.
        inactivity: 60
 
 
#Other configurable options
General:
    #Save online players accounts to database task. Disable this task and data will only be saved when the player disconnects.
    #To limit data loss in case the server crashes enable this saving task. It runs async so there will be no lag involved.
    saveDataTask:
        #Enable or disable the data save task. | (true or false)
        enabled: true
        #Time between data saves in minutes. | Default 3 min.
        interval: 3
        #Hide the data save task log messages.
        hideLogMessages: false
        
#End of file
#No seriously, whatelse did you expect in this config?
#Anyways goodluck with this plugin
#Be sure to rate this plugin on spigotmc!
#Also are you a BedWars player? Checkout screaming bedwars and screaming bedwars addon! 
#Help them reach 250k downloads!
#Thanks!